# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
cmd/husky:
  host: localhost:4443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 4443
    certPath: cmd/husky/.testdata/localhost.crt
    keyPath: cmd/husky/.testdata/localhost.key
  wintr/auth/ice:
    jwtSecret: bogus
cmd/husky-pack:
  host: localhost:5443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 5443
    certPath: cmd/husky-pack/.testdata/localhost.crt
    keyPath: cmd/husky-pack/.testdata/localhost.key
  wintr/auth/ice:
    jwtSecret: bogus
cmd/husky-bark:
  host: localhost:8443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 8443
    certPath: cmd/husky-bark/.testdata/localhost.crt
    keyPath: cmd/husky-bark/.testdata/localhost.key
  wintr/auth/ice:
    jwtSecret: bogus
  wintr/auth/firebase:
    allowEmailPassword: true
news: &news
  db: &newsDatabase
    urls:
      - localhost:3501
    user: admin
    password: pass
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5434/husky
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5434/husky
  messageBroker: &newsMessageBroker
    consumerGroup: husky-local-news-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &newsTopics
      - name: husky-news-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: news-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: viewed-news
        partitions: 10
        replicationFactor: 1
        retention: 1000h
  wintr/multimedia/picture:
    urlUpload: https://storage.bunnycdn.com/ice-staging/news
    urlDownload: https://ice-staging.b-cdn.net/news
notifications: &notifications
  deeplinkScheme: staging.ice.app
  pingCooldown: 1m
  disabledAchievementsNotifications:
    levels:
      - l6
    badges:
      - s1
      - c1
      - l1
  maxNotificationDelaySec: 60
  minNotificationDelaySec: 10
  notificationDelaysByTopic:
    news_en_v2:
      maxNotificationDelaySec: 60
      minNotificationDelaySec: 20
  wintr/multimedia/picture:
    urlDownload: https://ice-staging.b-cdn.net
  socials:
    - notificationType: follow_ion_on_x
      link: https://x.com/ice_blockchain/status/1743221098349535361
    - notificationType: follow_us_on_x
      link: https://x.com/ice_blockchain/status/1793988190614823165
    - notificationType: follow_zeus_on_x
      link: https://x.com/ice_blockchain/status/1793256299519418521
    - notificationType: join_ion_on_telegram
      link: https://x.com/ice_blockchain/status/1793256299519418521
    - notificationType: join_our_telegram
      link: https://x.com/ice_blockchain/status/1793256299519418521
  weeklyStats:
    weekday: 1
    hour: 10
    minutes: 0
  development: true
  db: &notificationsDatabase
    urls:
      - localhost:3501
    user: admin
    password: pass
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5434/husky
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5434/husky
  tenantName: BogusName
  tokenName: BN
  wintr/notifications/telegram:
    botToken: bogus
  telegramBots:
    bogusBot:
      botToken: bogus
  webAppLink: https://bogus.com/startapp
  messageBroker: &notificationsMessageBroker
    consumerGroup: husky-local-notifications-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &notificationsMessageBrokerTopics
      - name: husky-notifications-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: user-pings
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-device-metadata-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: adoption-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: news-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: available-daily-bonuses
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name:  achieved-badges
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-levels
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: enabled-roles
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: contacts-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: users-table
      - name: user-device-metadata-table
      - name: adoption-table
      - name: news-table
      - name: available-daily-bonuses
      - name: user-pings
      - name: achieved-badges
      - name: completed-levels
      - name: enabled-roles
      - name: contacts-table
      - name: mining-sessions-table
notifications_test:
  <<: *notifications
  messageBroker:
    <<: *notificationsMessageBroker
    consumingTopics: *notificationsMessageBrokerTopics
    consumerGroup: husky-local-notifications-test
  db:
    <<: *notificationsDatabase
news_test:
  <<: *news
  messageBroker:
    <<: *newsMessageBroker
    consumingTopics: *newsTopics
    consumerGroup: husky-local-news-test
  db:
    <<: *newsDatabase
